
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="smarterfarmers" #mandatory

version = "${version}"

displayName="Smarter Farmers" #mandatory

logoFile="icon.png" #optional

credits="MehVahdJukaar" #optional

authors="MehVahdJukaar" #optional

itemIcon="minecraft:carrot" #catalogue icon
description='''
Makes Farmer Villagers smarter!
'''

[[dependencies.smarterfarmers]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.smarterfarmers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.smarterfarmers]]

    modId="moonlight"
    mandatory=true
    versionRange="[1.19.2-2.0.35,]"
    ordering="AFTER"
    side="BOTH"
