modLoader = "javafml" #mandatory

loaderVersion = "[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license = "All rights reserved"

[[mods]] #mandatory

modId = "smarterfarmers" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Smarter Farmers" #mandatory
logoFile = "icon.png" #optional
credits = "Me" #optional
authors = "MehVahdJukaar" #optional

itemIcon = "minecraft:carrot" #catalogue icon
description = '''
    Makes Farmer Villagers smarter!
    '''

[[dependencies.smarterfarmers]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[40,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.smarterfarmers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smarterfarmers]]

modId = "moonlight"
mandatory = true
versionRange = "[1.19.2-2.0.16,]"
ordering = "NONE"
side = "SERVER"
